# Generated by Django 6.0.6 on 2026-06-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(default='500', max_length=50),
            preserve_default=False,
        ),
    ]
